---
title: Profi amod gydag os mewn dolen am byth
hero_image: images/banner.png
description: Galli di ddefnyddio datganiad os mewn dolen am byth i redeg blociau pryd bynnag mae amod yn gywir.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - 
    title: Profi amod mewn dolen am byth
