---
title: Kontrola podmínky s když uvnitř smyčky opakuj pořád
hero_image: images/banner.png
description: Použijte příkaz když uvnitř smyčky opakuj pořád ke spuštění bloků, kdykoli je podmínka pravdivá.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - title: Kontrola podmínky v příkazu opakuj pořád
