---
title: Comprobar que una condici贸n con 'si' se cumple dentro de un bucle por siempre
hero_image: images/banner.png
description: Usar una instrucci贸n 'si' dentro de un bucle por siempre para ejecutar bloques cada vez que una condici贸n sea verdadera.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - 
    title: Comprobar que una condici贸n se cumple dentro de un bucle por siempre
