---
title: Vérifier une condition avec si à l'intérieur d'une boucle infinie
hero_image: images/banner.png
description: Utiliser une instruction si dans une boucle infinie pour exécuter des blocs chaque fois qu'une condition est vraie.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - 
    title: Vérifier une condition à l'intérieur d'une boucle infinie
