---
title: Checking a condition with if inside a forever loop
hero_image: images/banner.png
description: Use an if statement inside a forever loop to run blocks whenever a condition is true.
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - 
    title: Checking a condition in a forever loop
